version: 2.1

orbs:
  hugo: circleci/hugo@1.2.2

jobs:
  deploy:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - attach_workspace:
          at: my-site
      - add_ssh_keys:
          fingerprints:
            - 02:55:fb:41:d1:ed:64:87:53:61:47:2f:b1:5f:f3:63
      - run: |
          export PATH=$PATH:/home/circleci/.local/bin
          pip install --user ghp-import
          ghp-import -n -p -f -c remy.greinho.fr -r origin -m "Published on $(date +"%Y-%m-%dT%H:%M:%S%Z")" my-site/public

workflows:
  main:
    jobs:
      - hugo/build:
          version: "0.87.0"
          html-proofer: false
      - deploy:
          requires:
            - hugo/build
          filters:
            branches:
              only: master
